name: ollama-marimo
services:
  ollama:
    runtime: nvidia
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - ollama-network
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_SCHED_SPREAD=false
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_CONTEXT_LENGTH=65536
    tty: true
    restart: unless-stopped
  marimo:
    build:
      context: ./marimo
      dockerfile: Dockerfile
    container_name: marimo
    command: ["marimo", "edit", "--no-token", "-p", "8080", "--host", "0.0.0.0"]
    ports:
      - "8080:8080"
    volumes:
      - ./data/marimo:/app
      - ./agent:/app/agent
      - ./catalogue:/app/catalogue
      - ./notebooks:/app/notebooks
    networks:
      - ollama-network
    environment:
      - MARIMO_SKIP_UPDATE_CHECK=1
    depends_on:
      - ollama
    restart: unless-stopped
networks:
  ollama-network:
    name: ollama-network
    external: false
