import inspect
import datetime
from agent.image_loader import (
    _build_readers, _resolve_path, _bioio_loader, bioio_loader,
    _normalise_to_uint8, prep_pipeline_image, _downsample_for_png, load_image,
)

CORE_DEPENDENCIES = [
    'bioio', 'bioio-tifffile', 'bioio-ome-tiff', 'bioio-czi',
    'bioio-imageio', 'bioio-lif', 'bioio-nd2',
    'numpy', 'imageio', 'scikit-image',
]

def _collect_dependencies(pipeline, catalogue) -> list[str]:
    """Aggregate package dependencies for exported script"""
    deps = set(CORE_DEPENDENCIES)
    seen_names = set()
    for step in pipeline:
        name = step['name']
        if name in seen_names:
            continue
        seen_names.add(name)
        metadata = catalogue[name]['metadata']
        deps.update(metadata.get('dependencies', []))
    return sorted(deps)

def build_pipeline_script(pipeline, catalogue, source_path, dims_override=None, 
                          t=0, z=None, channel=None, output_filename='output.png'):
    """
    Build standalone script for a particular run of the pipeline 
    that can be executed outwidth our repository i.e. is completely
    independent. 
    Uses filename and parameters chosen when building pipeline - these
    may be edited later after export.
    """
    lines = [
        '#!/usr/bin/env python3',
        '"""',
        f'Pipeline generated by AIBIO playground {datetime.datetime.now()}:',
        ' -> '.join(step['name'] for step in pipeline),
        '',
        'Edit image FILENAME (path) and function parameters at bottom of this script (see __main__) as needed.',
        '',
        'Dependencies: ',
        'pip install ' + ' '.join(_collect_dependencies(pipeline, catalogue)),
        '"""',
        'import io, os, tempfile',
        'import numpy as np',
        'import imageio.v3 as iio',
        'from bioio import BioImage',
        '',
        inspect.getsource(_build_readers),
        inspect.getsource(_resolve_path),
        inspect.getsource(_bioio_loader),
        inspect.getsource(bioio_loader),
        inspect.getsource(_normalise_to_uint8),
        inspect.getsource(prep_pipeline_image),
        inspect.getsource(_downsample_for_png),
        inspect.getsource(load_image),
    ]

    seen_names = set()
    for step in pipeline:
        name = step['name']
        if name in seen_names:
            continue
        seen_names.add(name)
        lines.append(f'# --- {name} ---')
        lines.append(inspect.getsource(catalogue[name]['function']))

    lines += [
        "if __name__ == '__main__':",
        f'    FILENAME = {source_path!r}',
        f'    OUTPUT_FILENAME = {output_filename!r}',
        f'    DIMS_OVERRIDE = {dims_override!r}',
        f'    T = {t!r}',
        f'    Z = {z!r}',
        f'    CHANNEL = {channel!r}',
        '    _, _array = load_image(FILENAME, dims_override=DIMS_OVERRIDE, t=T, z=Z, channel=CHANNEL)',
        "    image_data = {'source': _array, 'current': _array, 'info': {}}",
    ]

    for step in pipeline:
        name = step['name']
        params = {
            k: v for k, v in catalogue[name]['metadata']['parameters'].items()
            if k != 'image_data'
        }
        kwargs = step['args'] # With LLM or user-chosen params
        call_args = ', '.join(
            f'{pname}={kwargs.get(pname, catalogue[name]["defaults"].get(pname))!r}'
            for pname in params
        )
        lines.append(f'    image_data = {name}(image_data{", " + call_args if call_args else ""})') # fallback to catalogue defaults

    lines += [
        '    if image_data.get("info"):',
        '        print("Info:", image_data["info"])',
        '    iio.imwrite(OUTPUT_FILENAME, image_data["current"])',
        '    print(f"Saved result to {OUTPUT_FILENAME}")',
    ]

    return '\n'.join(lines)
