FROM squidfunk/mkdocs-material:9.6.16

# mkdocs-marimo provides `marimo` plugin 
# [imaging] provides `social` plugin 
RUN pip install --no-cache-dir \
    mkdocs-marimo \
    mkdocs-material[imaging]
