name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build app image
        run: docker build -t marimo-app -f marimo/Dockerfile .
      - name: Build test image
        run: docker build -t catalogue-test -f marimo/Dockerfile.test marimo
      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace catalogue-test pytest tests
